name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.14.0
  - ipython=7.21.0
  - notebook=6.2.0
  - jupyterlab=3.0.10
  - cookiecutter=1.7.2
  - hydra-core=1.3.2
  - matplotlib=3.3.4
  - pandas=2.0.3
  - git=2.34.1
  - pip=23.3.2
  - pip:
      - wandb==0.17.2
