name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.3
  - pip=23.3.2
  - mlflow=2.14.0
  - scikit-learn=1.5.0
  - pip:
      - wandb==0.17.2
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
