name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.3
  - pip=23.3.2
  - mlflow=2.14.0
  - scikit-learn=1.5.0
  - matplotlib=3.7.1
  - ipykernel
  - pillow=8.1.2
  - pip:
      - wandb==0.17.2
